### ISSUE TITLE
[RFC] Rename WordpressStandardTheme to AppTheme

### ISSUE THREAD

**Issue by benatespina** [LIN3S/WordpressStandard#22]
We should change "WordpressStandardTheme" to "AppTheme". In this way we should simplify the process to rename namespaces. Furthermore, we'll manage the namespaces in the same way that Symfony does with "AppBundle"

**Comment by benatespina** [comment]
@gorkalaucirica @jontorrado ping

**Comment by jontorrado** [comment]
I agree @benatespina

**Comment by benatespina** [comment]
This is the PR: #24
